### ISSUE TITLE
Push to supermarket

### ISSUE THREAD

**Issue by spuder** [Appdynamics/appdynamics-cookbooks#59] opened 2016-12-13 15:47 UTC
Any plans to push to the supermarket? 

Without the supermarket, users need to point berkshelf directly to a github ref or tag.

**Comment by dkoepke** [comment] 2016-12-21 23:01
Duplicate of #7. There's some internal hold ups on this, but it'll get done.

**Closed by dkoepke** 2016-12-21 23:01 UTC
