### ISSUE TITLE
Plans to add to supermarket

### ISSUE THREAD

**Issue by spuder** [Appdynamics/appdynamics-cookbooks#47] opened 2015-12-22 21:56 UTC
It appears that this cookbook isn't on the chef supermarket. Any plans to upload it there? Otherwise users have to do something like this in the berks file

```
source "https://supermarket.chef.io"

metadata

cookbook 'appdynamics', '~> 0.2.4', github: "Appdynamics/appdynamics-cookbooks", ref: "b87d05691717a9976b524ca2a42e9b641e22b7b6"
```

If you don't provide a git hash, then berks will automatically fetch from master. Most people don't know that and get burnt when a major version bump happens. (Other cookbooks have bit me in the past).

**Comment by spuder** [comment] 2016-09-12 19:42
@appdynamics is this cookbook still maintained? Still nothing on the supermarket

**Comment by dkoepke** [comment] 2016-09-12 19:44
Yes, the cookbook is still maintained. We will take a look at getting the
cookbook on Supermarket sooner rather than later.

**Comment by spuder** [comment] 2016-09-15 16:50
To share on the supermarket with knife

    knife cookbook site share "appdynamics" "<category>" -z --dry-run

Where <category> is one of the following

The cookbook category: "Databases", "Web Servers", "Process Management", "Monitoring & Trending", "Programming Languages", "Package Management", "Applications", "Networking", "Operating Systems & Virtualization", "Utilities", or "Other".

https://docs.chef.io/knife_cookbook_site.html

**Comment by dkoepke** [comment] 2016-09-19 21:14
Duplicate of #7. I'll upload to Supermarket soon.

**Closed by dkoepke** 2016-09-19 21:14 UTC
